import type { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Basic: Story;
export declare const Size: Story;
export declare const Shape: Story;
export declare const Icon: Story;
export declare const States: Story;
export declare const Block: Story;
export declare const AllVariants: Story;
